name: SAST Scan

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  semgrep-sast:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: returntocorp/semgrep-action@v1
        with:
          config: "auto"
